// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, wallet_address)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, wallet_address, two_factor_secret, two_factor_enabled, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at
`

type CreateUserParams struct {
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	WalletAddress pgtype.Text `json:"wallet_address"`
}

// internal/db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.WalletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WalletAddress,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, username, full_name, country)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, username, full_name, avatar_url, country, timezone, notifications_enabled, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Username pgtype.Text `json:"username"`
	FullName pgtype.Text `json:"full_name"`
	Country  pgtype.Text `json:"country"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.Username,
		arg.FullName,
		arg.Country,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Country,
		&i.Timezone,
		&i.NotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, wallet_address, two_factor_secret, two_factor_enabled, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WalletAddress,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, wallet_address, two_factor_secret, two_factor_enabled, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WalletAddress,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWallet = `-- name: GetUserByWallet :one
SELECT id, email, password_hash, wallet_address, two_factor_secret, two_factor_enabled, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at FROM users WHERE wallet_address = $1
`

func (q *Queries) GetUserByWallet(ctx context.Context, walletAddress pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWallet, walletAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.WalletAddress,
		&i.TwoFactorSecret,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, user_id, username, full_name, avatar_url, country, timezone, notifications_enabled, created_at, updated_at FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Country,
		&i.Timezone,
		&i.NotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoginAttempts = `-- name: UpdateLoginAttempts :exec
UPDATE users 
SET failed_login_attempts = $2, locked_until = $3, last_login = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateLoginAttemptsParams struct {
	ID                  uuid.UUID        `json:"id"`
	FailedLoginAttempts pgtype.Int4      `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamp `json:"locked_until"`
	LastLogin           pgtype.Timestamp `json:"last_login"`
}

func (q *Queries) UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) error {
	_, err := q.db.Exec(ctx, updateLoginAttempts,
		arg.ID,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastLogin,
	)
	return err
}

const updateUser2FA = `-- name: UpdateUser2FA :exec
UPDATE users 
SET two_factor_secret = $2, two_factor_enabled = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUser2FAParams struct {
	ID               uuid.UUID   `json:"id"`
	TwoFactorSecret  pgtype.Text `json:"two_factor_secret"`
	TwoFactorEnabled pgtype.Bool `json:"two_factor_enabled"`
}

func (q *Queries) UpdateUser2FA(ctx context.Context, arg UpdateUser2FAParams) error {
	_, err := q.db.Exec(ctx, updateUser2FA, arg.ID, arg.TwoFactorSecret, arg.TwoFactorEnabled)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profiles 
SET username = $2, full_name = $3, avatar_url = $4, country = $5, 
    timezone = $6, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

type UpdateUserProfileParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Username  pgtype.Text `json:"username"`
	FullName  pgtype.Text `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Country   pgtype.Text `json:"country"`
	Timezone  pgtype.Text `json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.UserID,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
		arg.Country,
		arg.Timezone,
	)
	return err
}
