// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID                pgtype.UUID      `json:"id"`
	TokenID           pgtype.UUID      `json:"token_id"`
	TotalValueLocked  pgtype.Numeric   `json:"total_value_locked"`
	CirculatingSupply pgtype.Numeric   `json:"circulating_supply"`
	MarketPrice       pgtype.Numeric   `json:"market_price"`
	PriceChange24h    pgtype.Numeric   `json:"price_change_24h"`
	Volume24h         pgtype.Numeric   `json:"volume_24h"`
	RecordedAt        pgtype.Timestamp `json:"recorded_at"`
}

type AuditLog struct {
	ID           pgtype.UUID      `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	Action       string           `json:"action"`
	ResourceType string           `json:"resource_type"`
	ResourceID   pgtype.Text      `json:"resource_id"`
	Details      []byte           `json:"details"`
	IpAddress    *netip.Addr      `json:"ip_address"`
	UserAgent    pgtype.Text      `json:"user_agent"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type GovernanceProposal struct {
	ID           pgtype.UUID      `json:"id"`
	Title        string           `json:"title"`
	Description  string           `json:"description"`
	ProposerID   pgtype.UUID      `json:"proposer_id"`
	ProposalType string           `json:"proposal_type"`
	Status       pgtype.Text      `json:"status"`
	VotingStart  pgtype.Timestamp `json:"voting_start"`
	VotingEnd    pgtype.Timestamp `json:"voting_end"`
	Quorum       pgtype.Numeric   `json:"quorum"`
	Threshold    pgtype.Numeric   `json:"threshold"`
	ForVotes     pgtype.Numeric   `json:"for_votes"`
	AgainstVotes pgtype.Numeric   `json:"against_votes"`
	AbstainVotes pgtype.Numeric   `json:"abstain_votes"`
	TotalVotes   pgtype.Numeric   `json:"total_votes"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type LiquidityPool struct {
	ID             pgtype.UUID      `json:"id"`
	Name           string           `json:"name"`
	Token0ID       pgtype.UUID      `json:"token0_id"`
	Token1ID       pgtype.UUID      `json:"token1_id"`
	TotalLiquidity pgtype.Numeric   `json:"total_liquidity"`
	Apr            pgtype.Numeric   `json:"apr"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type SecurityMonitor struct {
	ID          pgtype.UUID      `json:"id"`
	MetricName  string           `json:"metric_name"`
	MetricValue string           `json:"metric_value"`
	Severity    pgtype.Text      `json:"severity"`
	Status      pgtype.Text      `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Stake struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	TokenID        pgtype.UUID      `json:"token_id"`
	Amount         pgtype.Numeric   `json:"amount"`
	Apy            pgtype.Numeric   `json:"apy"`
	StartDate      pgtype.Timestamp `json:"start_date"`
	EndDate        pgtype.Timestamp `json:"end_date"`
	Status         pgtype.Text      `json:"status"`
	AutoCompound   pgtype.Bool      `json:"auto_compound"`
	RewardsClaimed pgtype.Numeric   `json:"rewards_claimed"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Token struct {
	ID              pgtype.UUID      `json:"id"`
	Symbol          string           `json:"symbol"`
	Name            string           `json:"name"`
	ContractAddress pgtype.Text      `json:"contract_address"`
	Decimals        pgtype.Int4      `json:"decimals"`
	IsActive        pgtype.Bool      `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID      `json:"id"`
	Email               string           `json:"email"`
	PasswordHash        string           `json:"password_hash"`
	WalletAddress       pgtype.Text      `json:"wallet_address"`
	TwoFactorSecret     pgtype.Text      `json:"two_factor_secret"`
	TwoFactorEnabled    pgtype.Bool      `json:"two_factor_enabled"`
	IsActive            pgtype.Bool      `json:"is_active"`
	FailedLoginAttempts pgtype.Int4      `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamp `json:"locked_until"`
	LastLogin           pgtype.Timestamp `json:"last_login"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type UserLiquidity struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	PoolID    pgtype.UUID      `json:"pool_id"`
	Amount0   pgtype.Numeric   `json:"amount0"`
	Amount1   pgtype.Numeric   `json:"amount1"`
	Shares    pgtype.Numeric   `json:"shares"`
	AprEarned pgtype.Numeric   `json:"apr_earned"`
	Status    pgtype.Text      `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserProfile struct {
	ID                   pgtype.UUID      `json:"id"`
	UserID               pgtype.UUID      `json:"user_id"`
	Username             pgtype.Text      `json:"username"`
	FullName             pgtype.Text      `json:"full_name"`
	AvatarUrl            pgtype.Text      `json:"avatar_url"`
	Country              pgtype.Text      `json:"country"`
	Timezone             pgtype.Text      `json:"timezone"`
	NotificationsEnabled pgtype.Bool      `json:"notifications_enabled"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type UserSession struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	AccessTokenHash  string           `json:"access_token_hash"`
	RefreshTokenHash string           `json:"refresh_token_hash"`
	UserAgent        pgtype.Text      `json:"user_agent"`
	IpAddress        *netip.Addr      `json:"ip_address"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	Revoked          pgtype.Bool      `json:"revoked"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type UserVote struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	ProposalID pgtype.UUID      `json:"proposal_id"`
	VotePower  pgtype.Numeric   `json:"vote_power"`
	VoteChoice string           `json:"vote_choice"`
	VotedAt    pgtype.Timestamp `json:"voted_at"`
}
