// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CastVote(ctx context.Context, arg CastVoteParams) (UserVote, error)
	// internal/db/queries/governance.sql
	CreateProposal(ctx context.Context, arg CreateProposalParams) (GovernanceProposal, error)
	// internal/db/queries/stakes.sql
	CreateStake(ctx context.Context, arg CreateStakeParams) (Stake, error)
	// internal/db/queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	GetActiveProposals(ctx context.Context) ([]GovernanceProposal, error)
	GetAssetMetrics(ctx context.Context) (GetAssetMetricsRow, error)
	GetProposalByID(ctx context.Context, id pgtype.UUID) (GovernanceProposal, error)
	GetStakeByID(ctx context.Context, id pgtype.UUID) (GetStakeByIDRow, error)
	GetTokenList(ctx context.Context) ([]GetTokenListRow, error)
	GetTotalStakedValue(ctx context.Context) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByWallet(ctx context.Context, walletAddress pgtype.Text) (User, error)
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	GetUserStakes(ctx context.Context, userID pgtype.UUID) ([]GetUserStakesRow, error)
	GetUserVotes(ctx context.Context, userID pgtype.UUID) ([]UserVote, error)
	Unstake(ctx context.Context, arg UnstakeParams) error
	// internal/db/queries/assets.sql
	UpdateAssetPrice(ctx context.Context, arg UpdateAssetPriceParams) error
	UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) error
	UpdateProposalVotes(ctx context.Context, arg UpdateProposalVotesParams) error
	UpdateStakeRewards(ctx context.Context, arg UpdateStakeRewardsParams) error
	UpdateUser2FA(ctx context.Context, arg UpdateUser2FAParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
